---
title: "Learn the basic knowledge of the biological data science"
author: "Engels Guyliann & Grosjean philippe"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---


## Abstract

We propose an inverse class of students to learn the biological data science with our learning tools in french. Students use the SVbox a virtual box with R and R studio and lots of other tools for reproducible research as Jupiter, Spyder, ... (add svbox app)

We use a website (package blogdown) to structure our lessons and ours tools. An e-book (bookdown package) is used for the theoretical notions. With each notion, interactive tutorials (learnr package) coupled to a database are proposed. The analysis of harvested data in a web apps (shiny package) easily enables to highlight the student difficulties and to improve the educational quality tools. We also can use this database to evaluate the students.

Students perform group work managed by GitHub Classroom. They use the RStudio projects to organise their work.  We have chosen to use Rmarkdown as a central tool to produce a report and notebook. our goal is to provide students with all the tools they need to conduct quality and reproducible research.
