---
title: "Application {shiny} de correction de projets individuels utilisant R, RStudio, GitHub"
author:
- Guyliann Engels 1^[Service d'écologie numérique, Institut Complexys & Infortech, Université de Mons, Belgique, guyliann.engels@umons.ac.be]
- Philippe Grosjean 2^[Service d'écologie numérique, Institut Complexys & Infortech, Université de Mons, Belgique, philippe.grosjean@umons.ac.be]
output: pdf_document
indent: true
bibliography: ref.bib
---

```{=tex}
\begin{center}
\textbf{Résumé (max 300 mots)}
\end{center}
```
Dans le cadre du cours de sciences des données biologiques à l'Université de Mons en Belgique, les étudiants réalisent des projets avec R et RStudio. Les projets sont rédigés en R Markdown et versionnés sur GitHub (organisation [BioDataScience-Course](https://github.com/BioDataScience-Course)) et générés via GitHub Classroom.

La correction des travaux est réalisée sur base de grilles critériées. Cette correction prend beaucoup de temps et nécessite une attention particulière pour obtenir une notation équitable d'un étudiant à l'autre, et si des commentaires constructifs sont ajoutés dans la grille.

Nous introduisons une nouvelle application web {shiny} permettant de corriger critère après critère tous les travaux en série. La partie concernée de chaque travail, identifié par un titre ou un label de chunk, est extraite des documents. Ces extraits sont regroupés et triés automatiquement avec un algorithme de calcul de similarité de texte du package {stringdist}. Ainsi, il est plus facile de noter de manière équivalente des réponses similaires. Cette manière de travailler diminue également le temps nécessaire à la correction. Des liens cliquables permettent d'accéder rapidement aux travaux complets, et au contexte éventuel (jeu de données, documents annexes, . . . ), améliorant ainsi encore la vitesse de correction et le confort d'utilisation dans le remplissage des grilles critériées.

\noindent \textbf{Mots-clefs} : Science des données biologiques -- Application shiny -- Pédagogie -- Correction -- Projet RStudio -- GitHub -- R Markdown

## Développement

R est enseigné dans les [cours de science des données](https://wp.sciviews.org) du cursus en biologie de l'Université de Mons, en Belgique (sur les quatre dernières années du cursus en cinq ans). Les cours, donnés en classe inversée, intègrent des éléments de statistiques, de reproductibilité, de données ouvertes ou encore d'Open Science. Le package {learnitdown} (@learnitdown) nous permet de gérer nos différents outils d'apprentissage {[bookdown](https://cran.r-project.org/web/packages/bookdown/index.html)}, [h5p](https://h5p.org/), {[learnr](https://cran.r-project.org/web/packages/learnr/index.html)}, {[shiny](https://cran.r-project.org/web/packages/shiny/index.html)} et les projets individuels ou de groupes sur [GitHub](https://github.com/).

Les projets se concrétisent par la réalisation d'un rapport traitant d'analyse de données biologiques. Ils sont générés à l'aide de [GitHub Classroom](https://classroom.github.com/), une application qui crée le dépôt pour chaque étudiant sur base d'un template GitHub. Ce template contient un squelette de document R Markdown (@rmarkdown) ou Quarto (@quarto) prérempli avec des balises permettant d'identifier les différentes parties du document (titres, labels de chunk...).

Un clone des différents dépôts GitHub contenant les projets est réalisé grâce à un script R dans un sous-dossier de la structure de l'app {shiny} (@shiny) et chaque document R Markdown est compilé.

Les grilles de correction sont initialisées automatiquement sur base d'un template pour chaque étudiant par un script R ou au démarrage de l'application {shiny}. La correction de certains critères est automatisée ou semi automatisée à ce stade. La grille template contient du code R qui est exécuté. Il analyse le projet de l'étudiant et remplit automatiquement la note et/ou le commentaire des critères en question. Ce code R peut, par exemple, vérifier si un étudiant a réalisé au moins un commit dans un document, si un document R Markdown compile, ou si un objet R généré est conforme à la solution attendue.

Une fois démarrée, l'application {shiny} contient :

-   une liste déroulante pour choisir le projet à corriger
-   une liste déroulante pour choisir le critère de la grille
-   une table qui reprend en ligne le résultat de chaque étudiant relatif à ce projet et à ce critère

Dans cette table les colonnes représentent les informations suivantes : la note et le commentaire (entrés par l'utilisateur de l'application), l'extrait correspondant du rapport de l'étudiant et les liens relatifs à cette entrée. Comme chaque critère est associé à un nom de section ou un label de chunk dans un document R Markdown, cela permet d'extraire grâce au package {parsermd} (@parsermd) la partie concernée de ce document et de l'afficher dans la table. Ces extraits sont comparés grâce à un algorithme de calcul de similarité de texte du package {stringdist} (@RJ-2014-011) puis regroupés par classification hiérarchique ascendante. De ce fait, les lignes de la table sont triées par similarité.

Une fois l'application {shiny} lancée, les correcteurs n'ont plus qu'à remplir ou modifier la colonne note et commentaire sur base de l'extrait du projet qui est affiché juste à côté. Les grilles correspondantes sont directement complétées. De plus, un résumé de l'état de progression de la correction pour l'ensemble des projets est affiché à la demande.

En conclusion, l'application offre la possibilité de corriger les projets des étudiants (documents R Markdown ou Quarto) rapidement et confortablement sur base de grilles critériées. Elle permet une notation équitable et objective d'un étudiant à l'autre grâce à la correction critère par critère avec tri par similarité des réponses. La proximité de ces réponses dans la table facilite l'ajout de commentaires détaillés en un minimum de temps. Ces commentaires permettent à l'étudiant de comprendre précisément sa note et les éléments clés pour s'améliorer.

## Références
