---
title: "Rendons les étudiants acteurs de leur propre apprentissage de la science des données biologiques."
author: "Engels Guyliann & Grosjean Philippe"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dans le cadre de la journée des enseignants du 15 mars 2019, nous organisons 2 stand afin de présenter notre philisophie d'apprentissage de la science des données biologiques.

Ce dossier comprend l'ensemble des ressources employées pour ce stand.

## Résumé

Les étudiants du bloc 2 du bachelier en biologie  ont suivi le nouveau cours de science des données biologique I : visualisation et inférence cette année 2018-2019. Ce dernier se nommait biostatistique et probabilités les années précédentes. Il était principalement orienté sur la mise en pratique des concepts de biostatistiques dans R (programme libre dédié au statistique) et RStudio (Interface pour utiliser R). Ce cours comptait 25 heures de théorie pour 50 heures de travaux pratiques. En règle générale chaque séance de cours de 2 heures était suivi d’une séance de tp de 4h. Malgré un cours orienté sur la pratique avec la totalité des notions étudiées avec des exemples biologiques, les étudiants se montraient plutôt passifs durant les cours et leurs enthousiasmes étaient bas. La maitrise des outils en était inévitablement plutôt faible.

Le changement du nom de ce cours a été de pair avec une remise en question profonde sur les notions indispensables à connaitre en tant que biologiste en science des données ainsi que sur la méthode d’enseignement. Les notions importantes ont été précisément définie et répartie entre les cours de science des données I à V (dont les cours I, II et III sont des cours obligatoires durant le cursus en biologie). Ces étudiants sont donc les premiers à rentrer dans la nouvelle philosophie proposée pour apprendre la science des données biologiques sur 4 années continues. 

Notre méthode d’enseignement se voit totalement revue. Nous avons décidé d’abandonner le cours ex cathedra afin de proposer un apprentissage sous la forme d’une classe inversé. Notre cours ne se divise de se fait plus en une succession de cours théoriques et de TP mais en une succession cohérente de … modules (12 modules pour le cours Science des données biologiques I) de 6h en présentiel chacun où les étudiants sont les acteurs de leurs apprentissages. 

Afin d’atteindre les objectifs de chaque module, les étudiants ont à leur disposition plusieurs outils comme une livre en ligne, une multitude de ressources supplémentaires, des vidéos, des quizz et des travaux de groupes à réaliser. Le livre en ligne est la source qui centralise l’ensemble des outils et structure leurs apprentissages. Il comprend les notions théoriques associé à des exemples biologiques. Ces notions sont appliquées sur des quizz intéractifs (learnr) à réaliser dans R et RStudio. Toutes leurs réponses sont collectées et sauvegardés dans une base de données. De manière transversale, des travaux de groupe sont également à réaliser et couvre plusieurs modules. Ces travaux favorisant la collaboration entre les étudiants sont géré avec GitHub et GitHub Classroom. 

Via la base de données et l’outil de gestion GitHub Classroom, nous récuperons l’ensemble des réponses des quiz et des travaux de groupes. Nous pouvons avec ces informations fournir aux étudiants un état d’avancement de leur progression.

Les résultats obtenus sont très encourageant. Nous observons une très forte participation à tous les quizz en ligne, à tous les travaux de groupes ainsi qu’à l’examen final (qui fut proposé sous la forme d’un learnR afin de rester cohérent avec les outils d’apprentissages que nous leur avons proposé durant l’année).  Les étudiants plus motivé que par le passé, ont montré une maitrise des outils (R et Rstudio) bien plus avancée que les étudiants précédents. 

Enfin, après avoir obtenu des résultats très intéressants avec nos étudiants, nous allons continuer à développer nos outils afin d’encore améliorer les outils mis à leur disposition pour aider à leur propre apprentissage comme rendre le livre en ligne et les vidéos interactifs avec des questions directement en son sein, diversifier et augmenter le nombre de quiz interactifs,…
