---
title: "Utilisation de tutoriels learnrs pour évaluer des étudiants en science des données biologiques"
author:
  - Guyliann Engels 1^[Service d'écologie numérique, Institut Complexys & Infortech, Université de Mons, Belgique, guyliann.engels@umons.ac.be]
  - Philippe Grosjean 1^[Service d'écologie numérique, Institut Complexys & Infortech, Université de Mons, Belgique, philippe.grosjean@umons.ac.be]
format: typst
indent: true
lang: fr
---

```{=typst}
#align(center)[#strong[Résumé (max 300 mots)]]
```

Nous présentons un dispositif d'évaluation continue sur ordinateur, basé sur R et learnr, permettant aux étudiants de rédiger des réponses contenant du code R qu'ils peuvent tester durant l'épreuve dans un processus R dont l'utilisation est strictement cadrée (grâce à Safe Exam Browser et AppArmor).

Le dispositif s’appuie sur des tutoriels interactifs {learnr} publiés via un serveur Posit Connect. Un "Learning Record Store" (LRS) dédié collecte les réponses aux questions dans le learnr. Ce dernier est généré à partir d'un document R Markdown contenant des balises spéciales supplémentaires qui permettent également de générer un second document HTML de correction des épreuves pour chaque étudiant (reprenant les questions et les réponses que l'étudiant a fournies, ainsi que la note et les commentaires de l'enseignant qui a corrigé l'épreuve).

Les fonctionnalités permettant de générer ces différents documents sont gérées par les packages de la plateforme d'apprentissage en R learnitr (https://learnitr.r-universe.dev). Cette dernière facilite également la correction des épreuves grâce à une interface Shiny (package {learnitgrid}).

Cette forme d'évaluation régulière (tous les 15 jours dans notre cas) est très appréciée par les étudiants, en particulier parce que la rédaction du code R dans les réponses est plus naturelle qu'avec un format ne permettant pas l'interaction avec un processus R (épreuves écrites sur papier par exemple).

**Mots-clefs (3 à 5)** : Enseignement - Évaluation continue - learnr - learnitr 


## Développement 

Dans le cadre des cours de sciences des données biologiques donnés à l’Université de Mons (Belgique, voir https://wp.sciviews.org), 108 étudiants, de la seconde à la quatrième année du cursus en biologie et répartis en trois cours successifs, sont évalués via des questionnaires interactifs ([voir l'exemple ici](https://github.com/BioDataScience-Course/sdd_presentations/tree/master/2026_rencontresr_nantes/learnr_exam/learnr_posit)). Ces questionnaires sont basés sur les packages {learnr} (https://rstudio.github.io/learnr/) et {learnitdown} (https://learnitr.r-universe.dev/learnitdown, par l'intermédiaire d'un package spécifique au cours qui configure l'environnement, dans le cas de l'exemple, c'est le package [{BioDataScience2}](https://github.com/BioDataScience-Course/BioDataScience2)). Ces learnrs sont publiés sur Posit Connect. Chaque étudiant est évalué tous les 15 jours en moyenne, selon une progression rythmée dès le départ sur base d'un planning de travail précis (voir par exemple <https://wp.sciviews.org/sdd-umons2/?iframe=wp.sciviews.org/sdd-umons2-2025/planning.html> pour le second cours).

Durant le premier quadrimestre, 41 questionnaires composés de 298 questions ont été rédigés. Ils se répartissent en 61 questions à choix multiples, 81 questions ouvertes et 156 questions nécessitant la rédaction de code R. Les réponses soumises par les étudiants ont généré 45 156 entrées dans le référentiel de données d’apprentissage ("Learning Record Store" ou LRS, récoltant les traces d'activité des étudiants dans les learnrs). Les étudiants peuvent soumettre autant de réponses que souhaité, mais seule la dernière est prise en compte pour la cotation. Chaque épreuve est limitée dans le temps et se fait à cahier ouvert ou fermé, selon le cas. Les données collectées sont bien sûr utilisées pour coter les étudiants, mais également pour obtenir des données quantitatives relatives à la difficulté des différentes questions. Un tel volume de questions et de réponses nous permet de déterminer la pertinence de cette approche.

Chaque questionnaire est conçu en R Markdown et remplit deux fonctions complémentaires ([voir un exemple d'un le matériel supplémentaire](https://go.sciviews.org/learnr_exam)). Premièrement, il sert de template pour le learnr formant le questionnaire sur Posit Connect. Deuxièmement, il intègre des balises particulières interprétées par un script qui le transforme en modèle de correction de l'épreuve. Ce dernier reprend les questions et permet de générer un document final pour chaque étudiant avec ses dernières réponses, ainsi que la note obtenue et les commentaires des enseignants qui les ont corrigées en rouge. Ces fichiers sont distribués par l'intermédiaire du rapport de progression de l'étudiant généré par le package {learnitprogress} (https://learnitr.r-universe.dev/learnitprogress).

Afin d'éviter que les étudiants n'utilisent d'autres ressources informatiques que celles fournies par le serveur Posit Connect du cours (https://sdd.umons.ac.be), ou par le site web correspondant (https://wp.sciviews.org) durant l'épreuve, Safe Exam Browser (https://safeexambrowser.org/start/start_en.html) est également utilisé. Il cadre l'utilisation de l'ordinateur par l'étudiant durant l'évaluation, tout en permettant d'accéder librement au learnr, et donc, à écrire et tester du code R pour les réponses qui le nécessitent. Le processus R utilisé par le learnr est lui-même exécuté sur le serveur dans un contexte protégé en utilisant AppArmor. L'intérêt principal de cette approche est donc bien dans l'interaction avec un processus R relativement proche de ce que l'étudiant peut utiliser dans, par exemple RStudio (le learnr offre également une aide à la complétion du code R), tout en restreignant par ailleurs le contexte de l'évaluation. Le retour des étudiants indique que cette façon d'interroger est grandement appréciée par rapport à des épreuves en version papier où l'écriture de code R est vue comme trop artificielle.

Du matériel supplémentaire — notamment un questionnaire, un corrigé ainsi que les rendus des learnr sur Posit Connect est disponible via le lien suivant : <https://go.sciviews.org/learnr_exam>
