---
title: "Des tableaux et des graphiques prêts à publication avec les packages R {tabularise} et {chart} de la suite SciViews"
author:
- Guyliann Engels 1^[Service d'écologie numérique, Institut Complexys & Infortech, Université de Mons, Belgique, guyliann.engels@umons.ac.be]
- Philippe Grosjean 2^[Service d'écologie numérique, Institut Complexys & Infortech, Université de Mons, Belgique, philippe.grosjean@umons.ac.be]
output: pdf_document
indent: true
bibliography: ref.bib
---

```{=tex}
\begin{center}
\textbf{Résumé (max 300 mots)}
\end{center}
```
Dans l’univers de R, plusieurs packages tels que {flextable} [@flextable], {gt} [@gt] ou encore {stargazer} [@stargazer] offrent des fonctionnalités de formatage de tableaux pour répondre aux normes de qualité des revues scientifiques. Bien que ces packages nécessitent de nombreuses lignes de code pour atteindre ces normes, ils permettent une personnalisation complète des tableaux. Cette situation est comparable à celle des packages dédiés à la génération de graphiques. Les graphiques sont réalisables avec le package {graphics} [@graphics], {lattice} [@lattice] ou encore {ggplot2} [@ggplot]. Les possibilités de personnalisation sont également nombreuses.

Au sein de la suite de packages SciViews [@sciviews] tels {[data.io](https://www.sciviews.org/data.io/)}, {[svFlow](https://www.sciviews.org/svFlow/)}, ou encore {[learnitdown](https://www.sciviews.org/learnitdown/)}, nous présentons {[tabularise](https://www.sciviews.org/tabularise)} pour les tableaux et {[chart](https://www.sciviews.org/chart/)} pour les graphiques. Ces outils s’appuient respectivement sur {flextable} et {ggplot2} pour offrir des tableaux et des graphiques représentant différents objets R, tels que **lm** ou **glm**, par exemple.

Ces tableaux et graphiques supportent l'anglais et le français et prennent également en compte les labels des variables pour fournir du contenu prêt à être publié avec un minimum d’instructions R. Ces outils visent à simplifier et à accélérer le processus de préparation des contenus à la publication.

\noindent \textbf{Mots-clefs} : Prêt à publication -- Tableau -- Graphique -- tabularise -- chart -- SciViews

## Développement

Lors de la rédaction de documents scientifiques, d’articles de blog ou encore de manuscrits de thèse, des outils tels que Rmarkdown [@rmarkdown] ou Quarto [@quarto] sont couramment utilisés. Ces outils permettent d’intégrer du code R dans des chunks et du texte en Markdown, ce qui constitue la première étape pour produire des documents prêts à être publiés. Cependant, une seconde étape est nécessaire pour créer des tableaux et des graphiques conformes aux normes de publication. Les sorties de base de R ne sont pas adaptées à cette fin, mais la communauté R propose de nombreuses solutions parmi les plus de 20 000 packages disponibles sur CRAN, sans compter ceux disponibles depuis BioConductor, GitHub ou Gitlab.

Pour la création de tableaux adaptés à la publication, on peut citer le package R {flextable} [@flextable] ou encore le package {gt} [@gt]. Ces outils puissants permettent de formater un tableau à partir d’un data frame. Ils offrent une grande flexibilité pour répondre à tous les besoins, mais nécessitent de nombreuses lignes de code pour obtenir le tableau dans le formatage souhaité. C’est pourquoi nous proposons, dans le cadre de SciViews, le package {tabularise}. Ce package permet d’obtenir des tableaux prêts à être publiés en une seule instruction pour une série d'objets dans R. Ces premières versions peuvent ensuite être remaniées à l'aide des instructions de {flextable}. {tabularise} gère l’anglais et le français et prend en compte automatiquement les labels fes variables si ils sont présents dans l'objet. De nombreuses méthodes sont disponibles. Certaines offrent des fonctionnalités supplémentaires au-delà de réalisation de tableaux. Par exemple, pour les objets **lm**, {tabularise} intègre également des équations dans son rendu en s'appuyant sur le package {equatiomatic} [@equatiomatic]. Ces caractéristiques en font un package intéressant pour la recherche et l’enseignement.

En ce qui concerne les graphiques, la communauté R propose principalement trois solutions : les packages R {graphics} [@graphics], {lattice} [@lattice] et {ggplot2} [@ggplot]. Le package {chart} propose une interface unique pour unifier ces trois moteurs graphiques, mais s'appuie principalement sur {ggplot2}. L’interface formule est utilisée, ce qui permet de se rapprocher des instructions que l’on peut utiliser, par exemple, dans la fonction `lm()`. Tout comme {tabularise}, {chart} s’adapte à l’anglais et au français. Il utilise les labels et les unités des variables pour libeller automatiquement les axes du graphique. De nombreuses méthodes ont été développées pour fournir des graphiques adaptés à toute une série d’objets.

En conclusion, {tabularise} et {chart} sont deux packages développés dans le cadre de SciViews pour faciliter et améliorer les sorties tabulaires et graphiques de R, prêts à être publiés.

## Références
